spring:
  datasource:
    url: jdbc:mysql://localhost:3306/resume_feedback?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: app
    password: app
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  main:
    banner-mode: "off"
  #spring:
   # flyway:
      #enabled: true
      #baseline-on-migrate: true
      #baseline-version: 1

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
