spring:
  datasource:
    url: jdbc:mysql://localhost:3306/resume_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: app
    password: app
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      spring.json.add.type.headers: false
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

app:
  storage:
    local-dir: C:/temp/resume-storage
  jwt:
    secret: mySecretKeyMySecretKeyMySecretKeyMySecretKeyMySecretKey
    issuer: resume-api
    expMinutes: 120


logging:
  level:
    org.springframework.security: DEBUG
