spring:
  datasource:
    url: jdbc:mysql://localhost:3306/resume_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: app
    password: app

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  data:
    mongodb:
      uri: mongodb://localhost:27017/resume_feedback_ai

app:
  storage:
    local-dir: C:/temp/resume-storage
  jwt:
    secret: mySecretKeyMySecretKeyMySecretKeyMySecretKeyMySecretKey
    issuer: resume-api
    expMinutes: 120

logging:
  level:
    org.springframework.security: DEBUG
