spring:
  data:
    redis:
      host: localhost
      port: 6379

app:
  storage:
    backend: S3
    s3:
      region: us-east-2
      bucket: feedback-fs
      cloudfront-url: https://d1ldjxzzmwekb0.cloudfront.net
      presign-expiration: 10m
