spring:
  datasource:
    url: jdbc:mysql://localhost:3306/resume_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: app
    password: app

  jpa:
    hibernate:
      ddl-auto: validate

  data:
    mongodb:
      uri: mongodb://localhost:27017/resume_feedback_ai
