spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: app
    password: app

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  mongodb:
    uri: ${SPRING_DATA_MONGODB_URI}

app:
  storage:
    backend: LOCAL
    local-dir: ./data/resume-storage
    s3:
      region: us-east-1
      presign-expiration: 10m
  jwt:
    secret: mySecretKeyMySecretKeyMySecretKeyMySecretKeyMySecretKey
    issuer: resume-api
    expMinutes: 120

logging:
  level:
    org.springframework.security: DEBUG
