spring:
  application:
    name: resume-api
  profiles:
    default: dev

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

app:
  ai-jobs:
    topic: resume-ai-jobs

logging:
  level:
    root: WARN

