spring:
  datasource:
    url: jdbc:mysql://localhost:3306/resume_feedback?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: app
    password: app
  jpa:
    hibernate:
      ddl-auto: update
#  flyway:
#    enabled: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

app:
  storage:
    local-dir: C:/temp/resume-storage
  jwt:
    secret: mySecretKeyMySecretKeyMySecretKeyMySecretKeyMySecretKey
    issuer: resume-api
    expMinutes: 120


#logging:
#  level:
#    org.springframework.security: DEBUG
#
