spring:
  data:
    redis:
      host: ${REDIS_URL}
      port: ${SPRING_DATA_REDIS_PORT}

app:
  storage:
    backend: S3
    s3:
      region: ${AWS_REGION}
      bucket: ${AWS_BUCKET}
      cloudfront-url: ${CLOUDFRONT_URL}
      presign-expiration: 10m
